#Ana Milosevic
#Pumpkin Patch

import turtle
import random
ana = turtle.Turtle()
ana.speed(1000)
degree = 90

def colorsky(): #creates the color of the sky w/o the moon or the stars
    ana.color("#070B34")
    ana.penup()
    ana.goto(-500,300)
    ana.pendown()
    ana.begin_fill()
    ana.forward(1000)
    ana.left(degree)
    ana.forward(100)
    ana.left(degree)
    ana.forward(1000)
    ana.left(degree)
    ana.forward(100)
    ana.end_fill()
    ana.color("#141852")
    ana.penup()
    ana.home()
    ana.goto(-500,225)
    ana.pendown()
    ana.begin_fill()
    ana.forward(1000)
    ana.left(degree)
    ana.forward(75)
    ana.left(degree)
    ana.forward(1000)
    ana.left(degree)
    ana.forward(75)
    ana.end_fill()
    ana.color("#2d196e")
    ana.penup()
    ana.home()
    ana.goto(-500,150)
    ana.pendown()
    ana.begin_fill()
    ana.forward(1000)
    ana.left(degree)
    ana.forward(75)
    ana.left(degree)
    ana.forward(1000)
    ana.left(degree)
    ana.forward(75)
    ana.end_fill()
    ana.color("#483475")
    ana.penup()
    ana.home()
    ana.goto(-500,75)
    ana.pendown()
    ana.begin_fill()
    ana.forward(1000)
    ana.left(degree)
    ana.forward(75)
    ana.left(degree)
    ana.forward(1000)
    ana.left(degree)
    ana.forward(75)
    ana.end_fill()

def stars(): #creates stars
    ana.color("white")
    ana.begin_fill()
    for i in range(20):
        ana.penup()
        ana.goto((random.randint(-500,500),random.randint(75,400)))
        ana.pendown()
        ana.begin_fill()
        for i in range(5):
            ana.forward(10)
            ana.left(144)
        ana.end_fill()

def moon(): #creates moon
    ana.color("white")
    ana.penup()
    ana.home()
    ana.goto(-250,300)
    ana.pendown()
    ana.begin_fill()
    ana.circle(75,360)
    ana.end_fill()


def tractorbody(): #creates the body of the tractor w/o window or wheels
    ana.color("red")
    ana.penup()
    ana.goto(-378,112)
    ana.pendown()
    ana.begin_fill()
    ana.forward(125)
    ana.circle(5,180)
    ana.forward(17)
    ana.right(degree)
    ana.forward(35)
    ana.left(degree)
    ana.forward(70)
    ana.right(degree)
    ana.forward(35)
    ana.left(degree)
    ana.forward(80)
    ana.left(degree)
    ana.forward(35)
    ana.right(degree)
    ana.forward(15)
    ana.left(degree)
    ana.forward(45)
    ana.left(degree)
    ana.forward(15)
    ana.end_fill()

def tractorwheel1(): #creates wheel on the front of the tractor
    ana.color("black")
    ana.penup()
    ana.home()
    ana.goto(-400,100)
    ana.pendown()
    ana.dot(50)
    ana.color("#839192")
    ana.penup()
    ana.goto(-400,100)
    ana.pendown()
    ana.dot(25)
    ana.color("#e59866")
    ana.penup()
    ana.goto(-400,100)
    ana.pendown()
    ana.dot(10)

def tractorwheel2(): #creates wheel on the back of the tractor
    ana.color("black")
    ana.penup()
    ana.home()
    ana.goto(-300,112)
    ana.pendown()
    ana.dot(75)
    ana.color("#839192")
    ana.penup()
    ana.goto(-300,112)
    ana.pendown()
    ana.dot(37.5)
    ana.color("#e59866")
    ana.penup()
    ana.goto(-300,112)
    ana.pendown()
    ana.dot(15)

def tractorwindow(): #creates the window on the tractor
    ana.penup()
    ana.goto(-410,150)
    ana.color("#2d196e")
    ana.pendown()
    ana.begin_fill()
    for i in range(2):
        ana.forward(25)
        ana.left(degree)
        ana.forward(35)
        ana.left(degree)
    ana.end_fill()
    ana.color("white")
    ana.pensize(3)
    ana.penup()
    ana.goto(-410,150)
    ana.pendown()
    for i in range(2):
        ana.forward(25)
        ana.left(degree)
        ana.forward(35)
        ana.left(degree)

def sky(): #combines all sky element functions into the whole sky function
    colorsky()
    stars()
    moon()

def tractor(): #combines all parts to the tractor into the whole tractor
    tractorbody()
    tractorwheel1()
    tractorwheel2()
    tractorwindow()

sky()
tractor()
ana.penup()

#Pumpkin Patch

#Init
import turtle
import random
angie=turtle.Turtle()
angie.speed(100)

#Functions
    
def pumpkin_skin(stretch_wid, stretch_len, x, y,color):
    angie.color(color)
    angie.penup()
    angie.goto(x,y)  
    angie.shape("circle")
    angie.shapesize(stretch_wid, stretch_len)
    stump_id=angie.stamp()

def pumpkin():
    pumpkin_skin(6, 3, -40, 32,"#ff8000") #Left
    pumpkin_skin(7, 4, 0, 25,"#ff8000") #Middle
    pumpkin_skin(6, 3, 40, 32,"#ff8000") #Right
    pumpkin_skin(7,4,-60,50,"#ff8000") #Second row left
    pumpkin_skin(7,4,-30,50,"#ff8000") 
    pumpkin_skin(7,4,0,50,"#ff8000") #Second row middle
    pumpkin_skin(7,4,30,50,"#ff8000") #Second row right
    pumpkin_skin(7,4,60,50,"#ff8000")

def stem():
    angie.color("#00b300")
    angie.begin_fill()
    angie.penup()
    angie.goto(-20,155)
    angie.pendown()
    for i in range(4):
        angie.forward(40)
        angie.right(90)
    angie.end_fill()

def pumpkin_skin_lines():
    angie.color("#b35900")
    angie.pensize(2)
    angie.penup()
    angie.goto(-45,115) #First line (left)
    angie.pendown()
    angie.left(-95)
    angie.forward(136)
    angie.penup()
    angie.goto(-20,118) #Second line (left)
    angie.pendown()
    angie.left(362)
    angie.forward(144)
    angie.penup()
    angie.goto(20,118)
    angie.pendown()
    angie.left(366)
    angie.forward(143)
    angie.penup()
    angie.goto(45,115)
    angie.pendown()
    angie.left(362)
    angie.forward(136)

def pumpkin_face():
    angie.left(85)
    angie.penup() 
    angie.goto(-60,50) #Right eye
    angie.pendown()
    angie.color("black")
    angie.begin_fill()
    for i in range(3):
        angie.forward(35)
        angie.left(120)
    angie.end_fill()
    angie.penup()
    angie.goto(20,50) #Left eye
    angie.pendown()
    angie.color("black")
    angie.begin_fill()
    for i in range(3):
        angie.forward(35)
        angie.left(120)
    angie.penup()
    angie.goto(-14,30)#Nose
    angie.pendown()
    for i in range(3):
        angie.forward(25)
        angie.left(120)
    angie.end_fill()
    angie.penup()
    angie.goto(-30,15) #Mouth
    angie.pendown()
    angie.pensize(7)
    angie.left(270)
    angie.circle(30,180)

def land():
    angie.penup()
    angie.goto(-1000,75)  
    angie.pendown()
    angie.color("#006600") #Grass
    angie.begin_fill()
    for i in range(4):
        angie.forward(3000)
        angie.right(90)
    angie.end_fill()

def draw_all_pumpkin():
    pumpkin_skin(stretch_wid, stretch_len, x, y,color)
    pumpkin()
    stem()
    pumpkin_skin_lines
    pumpkin_face()

def draw_pumpkins():
    size=random.randint(10,300)
    for i in range(4):
        angie.penup()
        draw_all_pumpkin((6,3,(random.randint(-800,-800),random.randint(-800,-800),"orange")))
        angie.pendown()

#Function
land()
pumpkin()
stem()
pumpkin_skin_lines()
pumpkin_face()
angie.hideturtle()

#Ava Mendoza

import turtle
ava = turtle.Turtle()
def barn(): #makes barn and barn door/windows
    ava.speed(1000)
    ava.color("#b0270a")
    ava.penup()
    ava.goto(100,75)
    ava.pendown()
    ava.begin_fill()
    ava.left(90)
    ava.forward(60)
    ava.right(45)
    ava.forward(30)
    ava.right(15)
    ava.forward(30)
    ava.right(50)
    ava.forward(30)
    ava.right(20)
    ava.forward(35)
    ava.right(50)
    ava.forward(60)
    ava.right(90)
    ava.forward(100)
    ava.end_fill()
    ava.color("white")
    ava.penup()
    ava.right(180)
    ava.forward(100)
    ava.left(90)
    ava.forward(55)
    ava.right(45)
    ava.pendown()
    ava.begin_fill()    
    ava.forward(10)
    ava.left(95)
    ava.forward(43)
    ava.left(15)
    ava.forward(32)
    ava.left(60)
    ava.forward(40)
    ava.left(17)
    ava.forward(30)
    ava.left(90)
    ava.forward(10)
    ava.left(95)
    ava.forward(32)
    ava.right(24)   
    ava.forward(32)
    ava.right(62)
    ava.forward(30)
    ava.right(15)   
    ava.forward(40)
    ava.end_fill()
    ava.penup()
    ava.home()
    ava.goto(125,75)
    ava.color("white")
    ava.pendown()
    ava.begin_fill()
    ava.left(90)
    ava.pensize(8)
    for i in range(4):
        ava.forward(50)
        ava.right(90)
    ava.right(90)
    ava.forward(25)
    ava.left(90)
    ava.forward(50)
    for i in range(3):
        ava.right(90)
        ava.forward(25)
    ava.forward(25)
    ava.penup()
    ava.right(90)
    ava.forward(35)
    ava.right(90)
    ava.forward(15)
    ava.pendown()
    ava.pensize(5)
    for i in range(4):
        ava.forward(20)
        ava.left(90)
    ava.pensize(3)
    ava.left(45)
    ava.forward(28.3)
    ava.left(135)
    ava.forward(20)
    ava.left(135)
    ava.forward(28.3)
    ava.penup()
    ava.home()
    ava.pendown()

def sign(x,y,color):#makes sign
    ava.penup()
    ava.goto(x,y)
    ava.color(color)
    ava.pendown()
    ava.begin_fill()
    ava.left(90)
    ava.forward(125)
    ava.left(90)
    for i in range(2):
        ava.forward(75)
        ava.circle(-10,90)
    ava.forward(85)
    for i in range(2):
        ava.forward(75)
        ava.circle(-10,90)
    ava.forward(75)
    ava.left(90)
    ava.forward(125)
    ava.right(90)
    ava.forward(10)
    ava.end_fill()
    ava.penup()

def letters(): #makes lettering on sign
    ava.goto(180,-215)
    ava.color("white")
    ava.pensize(8)
    ava.pendown()
    ava.left(90)
    ava.forward(20)
    ava.right(180)
    ava.forward(20)
    ava.circle(-7,360)
    ava.penup()
    ava.goto(212,-215)
    ava.pendown()
    ava.circle(-8,360)
    ava.circle(-8,180)
    ava.forward(8)
    ava.penup()
    ava.goto(250,-215)
    ava.pendown()
    ava.left(90)
    ava.forward(15)
    ava.left(180)
    ava.forward(7.5)
    ava.right(90)
    ava.forward(10)
    ava.right(180)
    ava.forward(25)
    ava.penup()
    ava.goto(290,-209)
    ava.pendown()
    ava.right(90)
    ava.circle(10,180)
    ava.penup()
    ava.goto(310,-209)
    ava.pendown()
    ava.right(90)
    ava.forward(18)
    ava.right(180)
    ava.forward(6)
    ava.circle(-10,190)
    ava.forward(4)
    ava.penup()
    ava.home()

barn()
sign(250,-390,"#8c4d08")
letters()
